### ISSUE TITLE
Simplify CSS code for shared properties. 

### ISSUE THREAD

**Issue by josephtkim** [Nobody-Inhere/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. When you have multiple elements that have the same property and value, you can simplify by applying it to them at once. Here, the font-family and font-weight properties are shared by multiple elements. You can simplify this code like so,

```css
h1, .topic, .starting {
  font-family: Helvetica;
  font-weight: bold;
}
```
